[tool.poetry]
name = "sweteam"
version = "0.1.0"
description = "Software Engineering Team"
authors = ["Alan Tan <alan@alantan.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ollama = "^0.1.9"
openai = "^1.25.0"
pyyaml = "^6.0.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
