[tool.poetry]
name = "sweteam"
version = "0.1.0"
description = "Software Engineering Team"
authors = ["Alan Tan <alan@alantan.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ollama = "^0.1.9"
openai = "^1.25.0"
python-dotenv = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
